ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
getmReversi ()
setmReversi ($_mReversi)
getmSetting ()
setmSetting ($_mSetting)
getmCurColor ()
setmCurColor ($_mCurColor)
getmCpu ()
setmCpu ($_mCpu)
getmEdge ()
setmEdge ($_mEdge)
getmPassEnaB ()
setmPassEnaB ($_mPassEnaB)
getmPassEnaW ()
setmPassEnaW ($_mPassEnaW)
getmGameEndSts ()
setmGameEndSts ($_mGameEndSts)
getmPlayLock ()
setmPlayLock ($_mPlayLock)
getViewMsgDlg ()
setViewMsgDlg ($_viewMsgDlg)
getDrawSingle ()
setDrawSingle ($_drawSingle)
getCurColMsg ()
setCurColMsg ($_curColMsg)
getCurStsMsg ()
setCurStsMsg ($_curStsMsg)
__construct ()
コンストラクタ
__destruct ()
デストラクタ
reversiPlay ($y, $x)
リバーシプレイ
reversiPlaySub ($cpuEna, $tmpCol)
リバーシプレイサブ
reversiPlayEnd ()
リバーシプレイ終了
reversiPlayPass ($color)
リバーシプレイパス
reversiPlayCpu ($color, $cpuEna)
リバーシプレイコンピューター
drawUpdate ($assist)
マス描画更新
drawUpdateForcibly ($assist)
マス描画強制更新
reset ()
リセット処理
gameEndAnimExec ()
ゲーム終了アニメーション
sendDrawMsg ($y, $x)
描画メッセージ送信
sendDrawInfoMsg ($y, $x)
情報描画メッセージ送信
Private Member Functions
execMessage ($what, $obj)
メッセージ
ViewMsgDlgLocal ($title, $msg)
メッセージダイアログ
DrawSingleLocal ($y, $x, $sts, $bk, $text)
1マス描画
CurColMsgLocal ($text)
現在の色メッセージ
CurStsMsgLocal ($text)
現在のステータスメッセージ
Private Attributes
$_mReversi
リバーシクラス
$_mSetting
リバーシ設定クラス
$_mCurColor
現在の色
$_mCpu
CPU用ワーク
$_mEdge
CPU用角マスワーク
$_mPassEnaB
黒のパス有効フラグ
$_mPassEnaW
白のパス有効フラグ
$_mGameEndSts
ゲーム終了ステータス
$_mPlayLock
プレイロック
$_viewMsgDlg
メッセージコールバック
$_drawSingle
描画コールバック
$_curColMsg
現在の色メッセージコールバック
$_curStsMsg
現在のステータスメッセージコールバック
Detailed Description
リバーシプレイクラス
Definition at line 29 of file ReversiPlay.php.
Constructor & Destructor Documentation
__construct ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 96 of file ReversiPlay.php.
__destruct ()
デストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 138 of file ReversiPlay.php.
Member Function Documentation
CurColMsgLocal ($text) [private]
現在の色メッセージ
Parameters
in $text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 950 of file ReversiPlay.php.
Referenced by execMessage().
CurStsMsgLocal ($text) [private]
現在のステータスメッセージ
Parameters
in $text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 967 of file ReversiPlay.php.
Referenced by execMessage().
DrawSingleLocal ($y, $x, $sts, $bk, $text) [private]
1マス描画
Parameters
in $y Y座標
in $x X座標
in $sts ステータス
in $bk 背景
in $text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 933 of file ReversiPlay.php.
Referenced by execMessage().
drawUpdate ($assist)
マス描画更新
Parameters
in $assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 607 of file ReversiPlay.php.
Referenced by reversiPlay(), and reversiPlayCpu().
drawUpdateForcibly ($assist)
マス描画強制更新
Parameters
in $assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 640 of file ReversiPlay.php.
Referenced by reset().
execMessage ($what, $obj) [private]
メッセージ
Parameters
in $what
in $obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 818 of file ReversiPlay.php.
Referenced by drawUpdate(), drawUpdateForcibly(), gameEndAnimExec(), reset(), reversiPlay(), reversiPlayCpu(), reversiPlayEnd(), sendDrawInfoMsg(), and sendDrawMsg().
gameEndAnimExec ()
ゲーム終了アニメーション
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 715 of file ReversiPlay.php.
Referenced by reversiPlayEnd().
reset ()
リセット処理
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 665 of file ReversiPlay.php.
void reversiPlay ($y, $x)
リバーシプレイ
Parameters
in $y $y座標
in $x $x座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 152 of file ReversiPlay.php.
reversiPlayCpu ($color, $cpuEna)
リバーシプレイコンピューター
Parameters
in $color CPU色
in $cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 349 of file ReversiPlay.php.
Referenced by reversiPlaySub().
reversiPlayEnd ()
リバーシプレイ終了
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 276 of file ReversiPlay.php.
Referenced by reversiPlay(), and reversiPlaySub().
reversiPlayPass ($color)
リバーシプレイパス
Parameters
in $color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 327 of file ReversiPlay.php.
Referenced by reversiPlay(), and reversiPlaySub().
reversiPlaySub ($cpuEna, $tmpCol)
リバーシプレイサブ
Parameters
in $cpuEna
in $tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 246 of file ReversiPlay.php.
Referenced by reversiPlay().
sendDrawInfoMsg ($y, $x)
情報描画メッセージ送信
Parameters
in $y Y座標
in $x X座標
Returns
ありません
Date
2018.03.02
Definition at line 799 of file ReversiPlay.php.
Referenced by drawUpdate().
sendDrawMsg ($y, $x)
描画メッセージ送信
Parameters
in $y Y座標
in $x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 781 of file ReversiPlay.php.
Referenced by drawUpdate(), gameEndAnimExec(), reversiPlay(), and reversiPlayCpu().
ViewMsgDlgLocal ($title, $msg) [private]
メッセージダイアログ
Parameters
in $title タイトル
in $msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 912 of file ReversiPlay.php.
Referenced by reversiPlay(), reversiPlayEnd(), and reversiPlayPass().
The documentation for this class was generated from the following file:
Model/ReversiPlay.php